version: '3'

services:
  search:
    image: getmeili/meilisearch:v1.2
    ports:
      - '7700:7700'
    environment:
      - MEILI_MASTER_KEY=71X6L@4mdjmvq6%At6hFcs3wvlcROPfI
    volumes:
      - ./meili_data:/meili_data
  